refactor: update buildnow terraform actions to use local proxy for state backend

diff --git a/build-now/terraform-init/action.yaml b/build-now/terraform-init/action.yaml
--- a/build-now/terraform-init/action.yaml
+++ b/build-now/terraform-init/action.yaml
@@ -1,26 +1,26 @@
 name: BuildNow Terraform Init
-description: Initiate Terraform with build-now-core-api as HTTP backend
+description: Initiate Terraform with Sync as HTTP backend
 
 inputs:
   PLUGIN_NAME:
     required: true
     description: Name of the BuildNow Plugin
   TERRAFORM_DIRECTORY:
-    required: true
-    description: The path to the Terraform root directory
-  TERRAFORM_BASIC_USERNAME:
     required: false
-    description: (Deprecated) Basic Auth Username
-    default: pipeline
-  TERRAFORM_BASIC_PASSWORD:
-    required: true
-    description: Basic Auth Password
+    description: The path to the Terraform root directory
   TWILIO_API_KEY:
     required: true
     description: The Twilio API key
   TWILIO_API_SECRET:
     required: true
     description: The Twilio API secret
+  # Deprecated Inputs
+  TERRAFORM_BASIC_USERNAME:
+    required: false
+    description: (Deprecated) No longer has an effect
+  TERRAFORM_BASIC_PASSWORD:
+    required: false
+    description: (Deprecated) No longer has an effect
 
 runs:
   using: composite
@@ -31,7 +31,6 @@ runs:
         fail=""
         [[ -z "${{ inputs.PLUGIN_NAME }}" ]] && echo "::error::Missing PLUGIN_NAME in inputs" && fail=1
         [[ -z "${{ inputs.TERRAFORM_DIRECTORY }}" ]] && echo "::error::Missing TERRAFORM_DIRECTORY in inputs" && fail=1
-        [[ -z "${{ inputs.TERRAFORM_BASIC_PASSWORD }}" ]] && echo "::error::Missing TERRAFORM_BASIC_PASSWORD in inputs" && fail=1
         [[ -z "${{ inputs.TWILIO_API_KEY }}" ]] && echo "::error::Missing TWILIO_API_KEY in inputs" && fail=1
         [[ -z "${{ inputs.TWILIO_API_SECRET }}" ]] && echo "::error::Missing TWILIO_API_SECRET in inputs" && fail=1
 
@@ -42,30 +41,29 @@ runs:
       with:
         terraform_wrapper: false
 
-    - name: Get Core Api Info
+    - name: Start Backend Proxy
       shell: bash
-      id: coreApi
-      run: ${{ github.action_path }}/functions-service-info.sh build-now-core-api
+      run: |
+        -set m
+        ./backend-proxy.sh 3434 & server_pid=$!
+        echo "TF_BACKEND_PROXY_PID=$server_pid" >> "$GITHUB_ENV"
+      working-directory: ${{ github.action_path }}
       env:
         TWILIO_API_KEY: ${{ inputs.TWILIO_API_KEY }}
         TWILIO_API_SECRET: ${{ inputs.TWILIO_API_SECRET }}
-
-    - name: Check Core Api Endpoint
-      shell: bash
-      run:
-        ${{ github.action_path }}/check-core-endpoint.sh "${{steps.coreApi.outputs.BASE_URL}}" "${{inputs.PLUGIN_NAME}}"
-      env:
-        TERRAFORM_BASIC_USERNAME: ${{ inputs.TERRAFORM_BASIC_USERNAME }}
-        TERRAFORM_BASIC_PASSWORD: ${{ inputs.TERRAFORM_BASIC_PASSWORD }}
 
     - name: Terraform Init
       shell: bash
       working-directory: ${{ inputs.TERRAFORM_DIRECTORY }}
       run: |
-        terraform init \
-        -backend-config="address=${{steps.coreApi.outputs.BASE_URL}}/terraform-crud?plugin=${{inputs.PLUGIN_NAME}}" \
-        -backend-config="username=${{inputs.TERRAFORM_BASIC_USERNAME}}" \
-        -backend-config="password=${{inputs.TERRAFORM_BASIC_PASSWORD}}"
+        pingCheck=$(curl -X GET -m 5 http://localhost:3434/ping) || exit 1
+
+        if [[ "$pingCheck" != "pong" ]]; then
+          echo "::error::Failed to connect to Terraform Backend Proxy" >&2
+          exit 1
+        fi
+
+        terraform init -backend-config="address=http://localhost:3434/${{inputs.PLUGIN_NAME}}"
   
     - name: Terraform Validate
       shell: bash
