feat: input validation for composite actions

diff --git a/build-now/add-readonly-perm-sync/action.yaml b/build-now/add-readonly-perm-sync/action.yaml
--- a/build-now/add-readonly-perm-sync/action.yaml
+++ b/build-now/add-readonly-perm-sync/action.yaml
@@ -20,6 +20,18 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate Inputs
+      shell: bash
+      run: |
+        fail=0
+        [[ -z "${{ inputs.SYNC_SERVICE_SID }}" ]] && echo "::error::Missing SYNC_SERVICE_SID in inputs" && fail=1
+        [[ -z "${{ inputs.OBJECT_TYPE }}" ]] && echo "::error::Missing OBJECT_TYPE in inputs" && fail=1
+        [[ -z "${{ inputs.OBJECT_SID }}" ]] && echo "::error::Missing OBJECT_SID in inputs" && fail=1
+        [[ -z "${{ inputs.TWILIO_API_KEY }}" ]] && echo "::error::Missing TWILIO_API_KEY in inputs" && fail=1
+        [[ -z "${{ inputs.TWILIO_API_SECRET }}" ]] && echo "::error::Missing TWILIO_API_SECRET in inputs" && fail=1
+
+        [[ "$fail" != "0" ]] && exit 1
+
     - name: Update ${{ inputs.SYNC_SERVICE_SID }}/${{ inputs.OBJECT_TYPE }}/${{ inputs.OBJECT_SID }}/Permissions/READ_ONLY
       shell: bash
       run: |
diff --git a/get-twilio-resource-sid/action.yaml b/get-twilio-resource-sid/action.yaml
--- a/get-twilio-resource-sid/action.yaml
+++ b/get-twilio-resource-sid/action.yaml
@@ -34,6 +34,24 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Validate Inputs
+      shell: bash
+      run: |
+        fail=0
+        [[ -z "${{ inputs.TWILIO_AREA }}" ]] && echo "::error::Missing TWILIO_AREA in inputs" && fail=1
+        [[ -z "${{ inputs.API_TYPE }}" ]] && echo "::error::Missing API_TYPE in inputs" && fail=1
+
+        if [ "${{ inputs.TWILIO_AREA }}" != "taskrouter" ] || [ "${{ inputs.API_TYPE }}" != "Workspaces" ]; then
+          [[ -z "${{ inputs.JSON_TYPE }}" ]] && echo "::error::Missing JSON_TYPE in inputs" && fail=1
+          [[ -z "${{ inputs.SEARCH_BY }}" ]] && echo "::error::Missing SEARCH_BY in inputs" && fail=1
+          [[ -z "${{ inputs.SEARCH_VALUE }}" ]] && echo "::error::Missing SEARCH_VALUE in inputs" && fail=1
+        fi
+
+        [[ -z "${{ inputs.TWILIO_API_KEY }}" ]] && echo "::error::Missing TWILIO_API_KEY in inputs" && fail=1
+        [[ -z "${{ inputs.TWILIO_API_SECRET }}" ]] && echo "::error::Missing TWILIO_API_SECRET in inputs" && fail=1
+
+        [[ "$fail" != "0" ]] && exit 1
+
     - name: Get ${{ inputs.TWILIO_AREA }}:${{ inputs.VERSION }}:${{ inputs.API_TYPE }}
       id: get
       shell: bash
diff --git a/update-twilio-functions-variables/action.yaml b/update-twilio-functions-variables/action.yaml
--- a/update-twilio-functions-variables/action.yaml
+++ b/update-twilio-functions-variables/action.yaml
@@ -23,6 +23,17 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Validate Inputs
+      shell: bash
+      run: |
+        fail=0
+        [[ -z "${{ inputs.SERVICE_NAME }}" ]] && echo "::error::Missing SERVICE_NAME in inputs" && fail=1
+        [[ -z "${{ inputs.VARIABLES_ENV }}" ]] && echo "::error::Missing VARIABLES_ENV in inputs" && fail=1
+        [[ -z "${{ inputs.TWILIO_API_KEY }}" ]] && echo "::error::Missing TWILIO_API_KEY in inputs" && fail=1
+        [[ -z "${{ inputs.TWILIO_API_SECRET }}" ]] && echo "::error::Missing TWILIO_API_SECRET in inputs" && fail=1
+
+        [[ "$fail" != "0" ]] && exit 1
+
     - name: Update Environment Variables for ${{ inputs.SERVICE_NAME }} ${{ inputs.ENVIRONMENT_SUFFIX }}
       shell: bash
       run: |
