fix: exit 1 on deploy-twilio-functions if expected output is not provided

diff --git a/.github/workflows/deploy-twilio-functions.yaml b/.github/workflows/deploy-twilio-functions.yaml
--- a/.github/workflows/deploy-twilio-functions.yaml
+++ b/.github/workflows/deploy-twilio-functions.yaml
@@ -106,7 +106,8 @@ jobs:
           mkdir -p src/functions
           deployOutput=$(npx twilio-run@3.5.3 deploy --production \
             --username $TWILIO_API_KEY --password $TWILIO_API_SECRET --output-format json | jq '')
-          if [ "$?" != "0" ]; then
+          if [ "$?" != "0" ] || [ -z "$(echo "$deployOutput" | jq -r '.serviceSid // empty')" ]; then
+            echo "::error::Functions deployment has failed. Please check the run logs." >&2
             exit 1
           fi
           echo "$deployOutput" >&2
